/**
 * Curated, categorized emoji set for the picker. Bundled in-repo so the picker
 * works fully offline (Twemoji only affects how each glyph is drawn, not which
 * emoji exist). Each entry is [char, "space separated search keywords"].
 *
 * @typedef {[string, string]} EmojiEntry
 * @typedef {{ id: string, name: string, icon: string, emojis: EmojiEntry[] }} EmojiCategory
 * @type {EmojiCategory[]}
 */
export const EMOJI_CATEGORIES = [
  {
    id: "smileys",
    name: "Smileys & Emotion",
    icon: "😀",
    emojis: [
      ["😀", "grin smile happy face"],
      ["😃", "smile happy joy face"],
      ["😄", "smile happy laugh face"],
      ["😁", "grin beaming smile face"],
      ["😆", "laugh satisfied happy"],
      ["😅", "sweat laugh nervous"],
      ["😂", "joy laugh tears cry funny lol"],
      ["🤣", "rofl rolling laugh funny lol"],
      ["🙂", "slight smile face"],
      ["🙃", "upside down silly"],
      ["😉", "wink flirt"],
      ["😊", "blush smile happy shy"],
      ["😇", "innocent angel halo"],
      ["🥰", "love hearts adore smile"],
      ["😍", "love heart eyes adore"],
      ["🤩", "star struck amazed excited"],
      ["😘", "kiss blow love"],
      ["😗", "kiss face"],
      ["😚", "kiss closed eyes"],
      ["😙", "kiss smile"],
      ["😋", "yum tasty tongue delicious"],
      ["😛", "tongue playful"],
      ["😜", "wink tongue playful crazy"],
      ["🤪", "zany crazy silly goofy"],
      ["😝", "tongue squint"],
      ["🤑", "money mouth rich dollar"],
      ["🤗", "hug hands smile"],
      ["🤭", "hand over mouth giggle oops"],
      ["🤫", "shush quiet silence"],
      ["🤔", "thinking hmm consider"],
      ["🤐", "zipper mouth secret quiet"],
      ["🤨", "raised eyebrow skeptical suspicious"],
      ["😐", "neutral meh blank"],
      ["😑", "expressionless blank"],
      ["😶", "no mouth speechless blank"],
      ["😏", "smirk sly"],
      ["😒", "unamused meh annoyed"],
      ["🙄", "eye roll annoyed whatever"],
      ["😬", "grimace awkward"],
      ["🤥", "lying liar pinocchio"],
      ["😌", "relieved calm content"],
      ["😔", "pensive sad down"],
      ["😪", "sleepy tired"],
      ["🤤", "drool sleep"],
      ["😴", "sleep zzz tired"],
      ["😷", "mask sick ill"],
      ["🤒", "sick thermometer ill fever"],
      ["🤕", "hurt injured bandage"],
      ["🤢", "nauseated sick gross"],
      ["🤮", "vomit sick puke"],
      ["🤧", "sneeze sick tissue"],
      ["🥵", "hot heat sweat"],
      ["🥶", "cold freezing frozen"],
      ["🥴", "woozy dizzy drunk"],
      ["😵", "dizzy knocked out"],
      ["🤯", "mind blown shocked exploding"],
      ["🤠", "cowboy hat"],
      ["🥳", "party celebrate hat birthday"],
      ["😎", "cool sunglasses"],
      ["🤓", "nerd geek glasses"],
      ["🧐", "monocle inspect curious"],
      ["😕", "confused unsure"],
      ["😟", "worried concerned"],
      ["🙁", "frown slight sad"],
      ["😮", "wow surprised open mouth"],
      ["😯", "hushed surprised"],
      ["😲", "astonished shocked"],
      ["😳", "flushed embarrassed shocked"],
      ["🥺", "pleading puppy eyes beg"],
      ["😦", "frowning open mouth"],
      ["😨", "fearful scared"],
      ["😰", "anxious sweat nervous"],
      ["😥", "sad relieved disappointed"],
      ["😢", "cry sad tear"],
      ["😭", "sob cry bawling sad"],
      ["😱", "scream fear shocked"],
      ["😖", "confounded frustrated"],
      ["😣", "persevere struggle"],
      ["😞", "disappointed sad"],
      ["😓", "sweat sad"],
      ["😩", "weary tired frustrated"],
      ["😫", "tired exhausted"],
      ["🥱", "yawn bored tired"],
      ["😤", "triumph huff angry steam"],
      ["😡", "angry mad rage red"],
      ["😠", "angry mad"],
      ["🤬", "cursing swearing angry"],
      ["😈", "devil smiling horns"],
      ["👿", "devil angry imp horns"],
      ["💀", "skull dead death"],
      ["💩", "poop crap"],
      ["🤡", "clown"],
      ["👻", "ghost boo spooky"],
      ["👽", "alien ufo"],
      ["🤖", "robot bot"],
      ["😺", "cat smile happy"],
      ["😸", "cat grin"],
      ["😹", "cat joy tears"],
      ["😻", "cat heart eyes love"],
      ["🙀", "cat scream shock"],
      ["😽", "cat kiss"],
    ],
  },
  {
    id: "gestures",
    name: "People & Gestures",
    icon: "👋",
    emojis: [
      ["👋", "wave hi hello bye"],
      ["🤚", "raised back hand"],
      ["🖐️", "hand fingers splayed"],
      ["✋", "hand stop high five"],
      ["🖖", "vulcan spock"],
      ["👌", "ok perfect"],
      ["🤌", "pinched fingers italian"],
      ["🤏", "pinch small tiny"],
      ["✌️", "victory peace"],
      ["🤞", "fingers crossed luck hope"],
      ["🤟", "love you gesture"],
      ["🤘", "rock horns metal"],
      ["🤙", "call me shaka"],
      ["👈", "point left"],
      ["👉", "point right"],
      ["👆", "point up"],
      ["👇", "point down"],
      ["☝️", "point up index"],
      ["👍", "thumbs up like yes good approve"],
      ["👎", "thumbs down dislike no bad"],
      ["✊", "fist raised power"],
      ["👊", "fist bump punch"],
      ["🤛", "fist left"],
      ["🤜", "fist right"],
      ["👏", "clap applause bravo"],
      ["🙌", "raise hands celebrate praise"],
      ["👐", "open hands"],
      ["🤲", "palms up pray beg"],
      ["🤝", "handshake deal agree"],
      ["🙏", "pray thanks please hope namaste"],
      ["✍️", "writing hand"],
      ["💅", "nails polish manicure"],
      ["💪", "muscle strong flex biceps"],
      ["👀", "eyes look watch"],
      ["👁️", "eye look"],
      ["👄", "mouth lips"],
      ["👅", "tongue"],
      ["👶", "baby infant"],
      ["🧒", "child kid"],
      ["👦", "boy"],
      ["👧", "girl"],
      ["🧑", "person adult"],
      ["👨", "man"],
      ["👩", "woman"],
      ["🧓", "older person"],
      ["👴", "old man grandpa"],
      ["👵", "old woman grandma"],
      ["🧔", "beard man"],
      ["👮", "police cop officer"],
      ["🕵️", "detective spy"],
      ["💂", "guard"],
      ["👷", "construction worker"],
      ["🤴", "prince"],
      ["👸", "princess"],
      ["🧕", "headscarf woman"],
      ["🤵", "tuxedo groom"],
      ["👰", "bride wedding veil"],
      ["🤰", "pregnant"],
      ["🎅", "santa christmas"],
      ["🤶", "mrs claus christmas"],
      ["🦸", "superhero hero"],
      ["🦹", "supervillain villain"],
      ["🧙", "wizard mage"],
      ["🧚", "fairy"],
      ["🧛", "vampire"],
      ["🧜", "merperson mermaid"],
      ["🧝", "elf"],
      ["🚶", "walk pedestrian"],
      ["🏃", "run running"],
      ["💃", "dance woman"],
      ["🕺", "dance man"],
      ["👯", "dancers bunny ears"],
      ["🧗", "climb climbing"],
      ["🤦", "facepalm"],
      ["🤷", "shrug idk dunno"],
    ],
  },
  {
    id: "nature",
    name: "Animals & Nature",
    icon: "🐻",
    emojis: [
      ["🐶", "dog puppy"],
      ["🐱", "cat kitten"],
      ["🐭", "mouse"],
      ["🐹", "hamster"],
      ["🐰", "rabbit bunny"],
      ["🦊", "fox"],
      ["🐻", "bear"],
      ["🐼", "panda"],
      ["🐨", "koala"],
      ["🐯", "tiger"],
      ["🦁", "lion"],
      ["🐮", "cow"],
      ["🐷", "pig"],
      ["🐸", "frog"],
      ["🐵", "monkey"],
      ["🐔", "chicken"],
      ["🐧", "penguin"],
      ["🐦", "bird"],
      ["🐤", "chick baby bird"],
      ["🦆", "duck"],
      ["🦅", "eagle"],
      ["🦉", "owl"],
      ["🦇", "bat"],
      ["🐺", "wolf"],
      ["🐗", "boar"],
      ["🐴", "horse"],
      ["🦄", "unicorn"],
      ["🐝", "bee"],
      ["🐛", "bug caterpillar"],
      ["🦋", "butterfly"],
      ["🐌", "snail"],
      ["🐞", "ladybug"],
      ["🐜", "ant"],
      ["🕷️", "spider"],
      ["🐢", "turtle"],
      ["🐍", "snake"],
      ["🦎", "lizard"],
      ["🐙", "octopus"],
      ["🦑", "squid"],
      ["🦀", "crab"],
      ["🐠", "fish tropical"],
      ["🐟", "fish"],
      ["🐬", "dolphin"],
      ["🐳", "whale"],
      ["🦈", "shark"],
      ["🐊", "crocodile"],
      ["🐅", "tiger"],
      ["🦓", "zebra"],
      ["🦍", "gorilla"],
      ["🐘", "elephant"],
      ["🦏", "rhino"],
      ["🐪", "camel"],
      ["🐄", "cow"],
      ["🐖", "pig"],
      ["🐑", "sheep"],
      ["🐐", "goat"],
      ["🦌", "deer"],
      ["🐓", "rooster"],
      ["🦃", "turkey"],
      ["🕊️", "dove peace bird"],
      ["🐕", "dog"],
      ["🐈", "cat"],
      ["🌵", "cactus"],
      ["🌲", "tree evergreen"],
      ["🌳", "tree"],
      ["🌴", "palm tree"],
      ["🌱", "seedling plant"],
      ["🌿", "herb leaf"],
      ["☘️", "shamrock clover"],
      ["🍀", "four leaf clover luck"],
      ["🍁", "maple leaf autumn"],
      ["🍂", "fallen leaves autumn"],
      ["🍃", "leaf wind"],
      ["🌺", "hibiscus flower"],
      ["🌸", "cherry blossom flower"],
      ["🌼", "blossom flower"],
      ["🌻", "sunflower"],
      ["🌹", "rose flower"],
      ["🌷", "tulip flower"],
      ["💐", "bouquet flowers"],
      ["🍄", "mushroom"],
      ["🌍", "earth globe world"],
      ["🌙", "moon crescent night"],
      ["⭐", "star"],
      ["🌟", "star glowing"],
      ["✨", "sparkles shiny"],
      ["⚡", "lightning bolt zap"],
      ["🔥", "fire flame lit hot"],
      ["🌈", "rainbow"],
      ["☀️", "sun sunny"],
      ["⛅", "cloud sun"],
      ["☁️", "cloud"],
      ["🌧️", "rain cloud"],
      ["⛄", "snowman winter"],
      ["❄️", "snowflake cold winter"],
      ["💧", "droplet water"],
      ["🌊", "wave ocean water"],
    ],
  },
  {
    id: "food",
    name: "Food & Drink",
    icon: "🍔",
    emojis: [
      ["🍏", "green apple"],
      ["🍎", "apple red"],
      ["🍐", "pear"],
      ["🍊", "orange tangerine"],
      ["🍋", "lemon"],
      ["🍌", "banana"],
      ["🍉", "watermelon"],
      ["🍇", "grapes"],
      ["🍓", "strawberry"],
      ["🫐", "blueberries"],
      ["🍒", "cherries"],
      ["🍑", "peach"],
      ["🥭", "mango"],
      ["🍍", "pineapple"],
      ["🥥", "coconut"],
      ["🥝", "kiwi"],
      ["🍅", "tomato"],
      ["🥑", "avocado"],
      ["🍆", "eggplant"],
      ["🥔", "potato"],
      ["🥕", "carrot"],
      ["🌽", "corn"],
      ["🌶️", "pepper spicy hot chili"],
      ["🥒", "cucumber"],
      ["🥬", "lettuce greens"],
      ["🥦", "broccoli"],
      ["🧄", "garlic"],
      ["🧅", "onion"],
      ["🍄", "mushroom"],
      ["🥜", "peanut nuts"],
      ["🍞", "bread"],
      ["🥐", "croissant"],
      ["🥖", "baguette bread"],
      ["🥨", "pretzel"],
      ["🧀", "cheese"],
      ["🥚", "egg"],
      ["🍳", "fried egg cooking"],
      ["🥞", "pancakes"],
      ["🧇", "waffle"],
      ["🥓", "bacon"],
      ["🍔", "burger hamburger"],
      ["🍟", "fries chips"],
      ["🍕", "pizza"],
      ["🌭", "hotdog"],
      ["🥪", "sandwich"],
      ["🌮", "taco"],
      ["🌯", "burrito"],
      ["🥙", "pita wrap"],
      ["🍝", "pasta spaghetti"],
      ["🍜", "ramen noodles"],
      ["🍲", "stew pot"],
      ["🍣", "sushi"],
      ["🍱", "bento box"],
      ["🍙", "rice ball"],
      ["🍚", "rice"],
      ["🍛", "curry rice"],
      ["🍤", "shrimp fried"],
      ["🍦", "ice cream soft"],
      ["🍨", "ice cream"],
      ["🍧", "shaved ice"],
      ["🎂", "cake birthday"],
      ["🍰", "cake slice"],
      ["🧁", "cupcake"],
      ["🍮", "custard pudding"],
      ["🍭", "lollipop candy"],
      ["🍬", "candy sweet"],
      ["🍫", "chocolate"],
      ["🍿", "popcorn"],
      ["🍩", "donut doughnut"],
      ["🍪", "cookie"],
      ["☕", "coffee tea hot"],
      ["🍵", "tea green"],
      ["🥤", "soda cup drink"],
      ["🧃", "juice box"],
      ["🍺", "beer"],
      ["🍻", "beers cheers"],
      ["🥂", "champagne cheers toast"],
      ["🍷", "wine"],
      ["🍸", "cocktail martini"],
      ["🍹", "tropical drink cocktail"],
      ["🥃", "whiskey"],
      ["🍾", "champagne bottle celebrate"],
    ],
  },
  {
    id: "activities",
    name: "Activities",
    icon: "⚽",
    emojis: [
      ["⚽", "soccer football"],
      ["🏀", "basketball"],
      ["🏈", "american football"],
      ["⚾", "baseball"],
      ["🥎", "softball"],
      ["🎾", "tennis"],
      ["🏐", "volleyball"],
      ["🏉", "rugby"],
      ["🎱", "billiards pool 8 ball"],
      ["🏓", "ping pong table tennis"],
      ["🏸", "badminton"],
      ["🥅", "goal net"],
      ["🏒", "hockey"],
      ["🏑", "field hockey"],
      ["🥍", "lacrosse"],
      ["🏏", "cricket"],
      ["⛳", "golf flag"],
      ["🏹", "bow arrow archery"],
      ["🎣", "fishing"],
      ["🥊", "boxing glove"],
      ["🥋", "martial arts karate"],
      ["⛸️", "ice skate"],
      ["🎿", "ski"],
      ["🛷", "sled"],
      ["🏂", "snowboard"],
      ["🏋️", "weightlifting gym"],
      ["🤸", "cartwheel gymnastics"],
      ["🤼", "wrestling"],
      ["🤽", "water polo"],
      ["🤾", "handball"],
      ["🏌️", "golf"],
      ["🏇", "horse racing"],
      ["🧘", "yoga meditation"],
      ["🏄", "surf"],
      ["🏊", "swim"],
      ["🚴", "cycling bike"],
      ["🚵", "mountain bike"],
      ["🏆", "trophy win champion"],
      ["🥇", "gold medal first"],
      ["🥈", "silver medal second"],
      ["🥉", "bronze medal third"],
      ["🏅", "medal award"],
      ["🎖️", "military medal"],
      ["🎗️", "ribbon"],
      ["🎫", "ticket"],
      ["🎟️", "admission tickets"],
      ["🎪", "circus tent"],
      ["🎭", "theater masks drama"],
      ["🎨", "art palette paint"],
      ["🎬", "movie clapper film"],
      ["🎤", "microphone sing karaoke"],
      ["🎧", "headphones music"],
      ["🎼", "music score"],
      ["🎹", "piano keyboard"],
      ["🥁", "drum"],
      ["🎷", "saxophone"],
      ["🎺", "trumpet"],
      ["🎸", "guitar"],
      ["🎻", "violin"],
      ["🎲", "dice game"],
      ["♟️", "chess pawn"],
      ["🎯", "dart target bullseye"],
      ["🎳", "bowling"],
      ["🎮", "video game controller"],
      ["🕹️", "joystick game"],
      ["🎰", "slot machine gamble"],
      ["🧩", "puzzle piece"],
    ],
  },
  {
    id: "travel",
    name: "Travel & Places",
    icon: "🚗",
    emojis: [
      ["🚗", "car auto"],
      ["🚕", "taxi cab"],
      ["🚙", "suv car"],
      ["🚌", "bus"],
      ["🚎", "trolleybus"],
      ["🏎️", "race car fast"],
      ["🚓", "police car"],
      ["🚑", "ambulance"],
      ["🚒", "fire truck"],
      ["🚐", "van minibus"],
      ["🚚", "truck delivery"],
      ["🚜", "tractor"],
      ["🏍️", "motorcycle"],
      ["🛵", "scooter moped"],
      ["🚲", "bicycle bike"],
      ["🛴", "kick scooter"],
      ["🚨", "siren police alert"],
      ["🚔", "police car"],
      ["🚍", "bus oncoming"],
      ["✈️", "airplane flight travel"],
      ["🛫", "takeoff plane"],
      ["🛬", "landing plane"],
      ["🚀", "rocket launch space"],
      ["🛸", "ufo saucer"],
      ["🚁", "helicopter"],
      ["⛵", "sailboat"],
      ["🚤", "speedboat"],
      ["🛥️", "motor boat"],
      ["🚢", "ship cruise"],
      ["⚓", "anchor"],
      ["🚂", "train locomotive"],
      ["🚆", "train"],
      ["🚇", "metro subway"],
      ["🚊", "tram"],
      ["🚉", "station"],
      ["🚁", "helicopter"],
      ["🗺️", "map world"],
      ["🧭", "compass"],
      ["🏔️", "mountain snow"],
      ["⛰️", "mountain"],
      ["🌋", "volcano"],
      ["🏕️", "camping tent"],
      ["🏖️", "beach umbrella"],
      ["🏝️", "island"],
      ["🏜️", "desert"],
      ["🏙️", "cityscape city"],
      ["🌃", "night city stars"],
      ["🌆", "city dusk sunset"],
      ["🌇", "sunset city"],
      ["🌉", "bridge night"],
      ["🗽", "statue liberty"],
      ["🗼", "tokyo tower"],
      ["🏰", "castle"],
      ["🏯", "japanese castle"],
      ["🎡", "ferris wheel"],
      ["🎢", "roller coaster"],
      ["🎠", "carousel"],
      ["⛲", "fountain"],
      ["🏠", "house home"],
      ["🏡", "house garden home"],
      ["🏢", "office building"],
      ["🏥", "hospital"],
      ["🏦", "bank"],
      ["🏨", "hotel"],
      ["🏫", "school"],
      ["⛪", "church"],
      ["🕌", "mosque"],
      ["🗿", "moai statue"],
      ["🎑", "moon viewing"],
      ["🎇", "sparkler firework"],
      ["🎆", "fireworks"],
    ],
  },
  {
    id: "objects",
    name: "Objects",
    icon: "💡",
    emojis: [
      ["⌚", "watch time"],
      ["📱", "phone mobile"],
      ["💻", "laptop computer"],
      ["⌨️", "keyboard"],
      ["🖥️", "desktop computer monitor"],
      ["🖨️", "printer"],
      ["🖱️", "mouse computer"],
      ["💽", "minidisk"],
      ["💾", "floppy save disk"],
      ["💿", "cd disk"],
      ["📀", "dvd"],
      ["📷", "camera photo"],
      ["📸", "camera flash photo"],
      ["📹", "video camera"],
      ["🎥", "movie camera film"],
      ["📞", "telephone call"],
      ["☎️", "phone landline"],
      ["📟", "pager"],
      ["📠", "fax"],
      ["📺", "tv television"],
      ["📻", "radio"],
      ["🎙️", "studio microphone"],
      ["⏱️", "stopwatch timer"],
      ["⏰", "alarm clock"],
      ["🕰️", "clock mantel"],
      ["⏳", "hourglass time"],
      ["⌛", "hourglass done"],
      ["🔋", "battery"],
      ["🔌", "plug power"],
      ["💡", "bulb light idea"],
      ["🔦", "flashlight torch"],
      ["🕯️", "candle"],
      ["💰", "money bag rich"],
      ["💵", "dollar money cash"],
      ["💴", "yen money"],
      ["💶", "euro money"],
      ["💷", "pound money"],
      ["💳", "credit card"],
      ["💎", "gem diamond jewel"],
      ["⚖️", "scales justice balance"],
      ["🔧", "wrench tool fix"],
      ["🔨", "hammer tool"],
      ["🛠️", "tools hammer wrench"],
      ["⚙️", "gear settings cog"],
      ["🔩", "nut bolt screw"],
      ["🧲", "magnet"],
      ["🔫", "gun water pistol"],
      ["💣", "bomb"],
      ["🧨", "firecracker dynamite"],
      ["🔪", "knife cut"],
      ["🗡️", "dagger sword"],
      ["🛡️", "shield"],
      ["🚬", "cigarette smoking"],
      ["⚰️", "coffin"],
      ["🏺", "amphora vase"],
      ["🔮", "crystal ball fortune"],
      ["📿", "prayer beads"],
      ["💈", "barber pole"],
      ["🔭", "telescope"],
      ["🔬", "microscope science"],
      ["💊", "pill medicine"],
      ["💉", "syringe shot vaccine"],
      ["🩹", "bandage plaster"],
      ["🌡️", "thermometer temperature"],
      ["🧬", "dna"],
      ["🦠", "microbe germ virus"],
      ["🧪", "test tube science"],
      ["🧫", "petri dish"],
      ["🧴", "lotion bottle"],
      ["🧷", "safety pin"],
      ["🧹", "broom cleaning"],
      ["🧺", "basket laundry"],
      ["🧻", "toilet paper roll"],
      ["🚽", "toilet"],
      ["🚿", "shower"],
      ["🛁", "bathtub"],
      ["🔑", "key"],
      ["🗝️", "old key"],
      ["🚪", "door"],
      ["🛋️", "couch sofa"],
      ["🛏️", "bed"],
      ["🧸", "teddy bear toy"],
      ["🖼️", "picture frame"],
      ["🛒", "shopping cart"],
      ["🎁", "gift present box"],
      ["🎈", "balloon party"],
      ["🎉", "party popper celebrate tada"],
      ["🎊", "confetti party"],
      ["🎏", "carp streamer"],
      ["🎐", "wind chime"],
      ["🧧", "red envelope money"],
      ["✉️", "envelope mail letter"],
      ["📩", "email incoming"],
      ["📦", "package box parcel"],
      ["📫", "mailbox"],
      ["📝", "memo note write"],
      ["📖", "book open read"],
      ["📚", "books library"],
      ["📕", "book red"],
      ["📓", "notebook"],
      ["📅", "calendar date"],
      ["📌", "pushpin pin"],
      ["📎", "paperclip"],
      ["✂️", "scissors cut"],
      ["🖊️", "pen"],
      ["✏️", "pencil write"],
      ["🔍", "magnify search"],
      ["🔒", "lock secure"],
      ["🔓", "unlock open"],
    ],
  },
  {
    id: "symbols",
    name: "Symbols",
    icon: "❤️",
    emojis: [
      ["❤️", "red heart love"],
      ["🧡", "orange heart"],
      ["💛", "yellow heart"],
      ["💚", "green heart"],
      ["💙", "blue heart"],
      ["💜", "purple heart"],
      ["🖤", "black heart"],
      ["🤍", "white heart"],
      ["🤎", "brown heart"],
      ["💔", "broken heart sad"],
      ["❣️", "heart exclamation"],
      ["💕", "two hearts love"],
      ["💞", "revolving hearts"],
      ["💓", "beating heart"],
      ["💗", "growing heart"],
      ["💖", "sparkling heart"],
      ["💘", "heart arrow cupid"],
      ["💝", "heart gift ribbon"],
      ["💟", "heart decoration"],
      ["❤️‍🔥", "heart fire burning love"],
      ["💯", "hundred perfect score keep it"],
      ["💢", "anger symbol mad"],
      ["💥", "collision boom explosion"],
      ["💫", "dizzy star"],
      ["💦", "sweat droplets water"],
      ["💨", "dash wind fast"],
      ["🕳️", "hole"],
      ["💬", "speech balloon chat"],
      ["💭", "thought bubble"],
      ["💤", "zzz sleep"],
      ["✅", "check mark done yes green"],
      ["❌", "cross x no wrong"],
      ["❎", "cross mark button"],
      ["➕", "plus add"],
      ["➖", "minus subtract"],
      ["➗", "divide"],
      ["✖️", "multiply x"],
      ["❓", "question mark"],
      ["❔", "white question"],
      ["❗", "exclamation mark"],
      ["❕", "white exclamation"],
      ["‼️", "double exclamation"],
      ["⁉️", "exclamation question"],
      ["⭕", "circle o red"],
      ["🔴", "red circle"],
      ["🟠", "orange circle"],
      ["🟡", "yellow circle"],
      ["🟢", "green circle"],
      ["🔵", "blue circle"],
      ["🟣", "purple circle"],
      ["⚫", "black circle"],
      ["⚪", "white circle"],
      ["🟥", "red square"],
      ["🟩", "green square"],
      ["🟦", "blue square"],
      ["⬛", "black square"],
      ["⬜", "white square"],
      ["🔶", "orange diamond"],
      ["🔷", "blue diamond"],
      ["🔺", "red triangle up"],
      ["🔻", "red triangle down"],
      ["💠", "diamond dot"],
      ["🔘", "radio button"],
      ["⚠️", "warning caution"],
      ["🚫", "prohibited no"],
      ["♻️", "recycle"],
      ["✔️", "check tick"],
      ["🔞", "no under 18 adult"],
      ["📵", "no phones"],
      ["🔇", "mute no sound"],
      ["🔊", "loud speaker sound"],
      ["🔔", "bell notification"],
      ["🔕", "no bell muted"],
      ["🎵", "music note"],
      ["🎶", "music notes"],
      ["➰", "curly loop"],
      ["✳️", "eight spoked asterisk"],
      ["❇️", "sparkle"],
      ["©️", "copyright"],
      ["®️", "registered"],
      ["™️", "trademark"],
      ["🔟", "ten keycap"],
      ["🔢", "numbers input"],
      ["#️⃣", "hash keycap"],
      ["*️⃣", "asterisk keycap"],
      ["▶️", "play"],
      ["⏸️", "pause"],
      ["⏯️", "play pause"],
      ["⏹️", "stop"],
      ["⏭️", "next track"],
      ["⏮️", "previous track"],
      ["🔀", "shuffle"],
      ["🔁", "repeat loop"],
      ["🔂", "repeat one"],
      ["🔄", "refresh sync arrows"],
      ["⬆️", "up arrow"],
      ["⬇️", "down arrow"],
      ["⬅️", "left arrow"],
      ["➡️", "right arrow"],
      ["↔️", "left right arrow"],
      ["↩️", "return arrow"],
      ["🔝", "top up"],
      ["🆗", "ok button"],
      ["🆒", "cool button"],
      ["🆕", "new button"],
      ["🆓", "free button"],
      ["💲", "dollar sign money"],
      ["💱", "currency exchange"],
    ],
  },
  {
    id: "flags",
    name: "Flags",
    icon: "🏳️",
    emojis: [
      ["🏁", "checkered flag finish race"],
      ["🚩", "triangular flag"],
      ["🎌", "crossed flags japan"],
      ["🏴", "black flag"],
      ["🏳️", "white flag surrender"],
      ["🏳️‍🌈", "rainbow flag pride lgbt"],
      ["🏴‍☠️", "pirate flag skull"],
      ["🇺🇸", "usa united states america flag"],
      ["🇬🇧", "uk united kingdom britain flag"],
      ["🇨🇦", "canada flag"],
      ["🇦🇺", "australia flag"],
      ["🇩🇪", "germany flag"],
      ["🇫🇷", "france flag"],
      ["🇪🇸", "spain flag"],
      ["🇮🇹", "italy flag"],
      ["🇯🇵", "japan flag"],
      ["🇰🇷", "korea flag"],
      ["🇨🇳", "china flag"],
      ["🇮🇳", "india flag"],
      ["🇧🇷", "brazil flag"],
      ["🇷🇺", "russia flag"],
      ["🇺🇦", "ukraine flag"],
      ["🇲🇽", "mexico flag"],
      ["🇳🇱", "netherlands flag"],
      ["🇸🇪", "sweden flag"],
      ["🇳🇴", "norway flag"],
      ["🇵🇱", "poland flag"],
      ["🇹🇷", "turkey flag"],
    ],
  },
];
